"""
Load all CSV files into PostgreSQL, then seed tmdb_account and user_rating.

Usage:
    python scripts/load_csv_to_postgres.py

Reads connection settings from .env (or environment variables):
    POSTGRES_HOST      default: localhost
    POSTGRES_PORT      default: 5433
    POSTGRES_DB        default: movie_recommender
    POSTGRES_USER      default: postgres
    POSTGRES_PASSWORD  required

Steps:
  1. Load all CSV tables in FK-dependency order (fast COPY, fallback INSERT).
  2. Derive tmdb_account rows from unique review authors.
  3. Derive user_rating rows from reviews that carry a numeric author_rating.
"""

import csv
import io
import os
import sys
from pathlib import Path

import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_CONFIG = {
    "host":     os.getenv("POSTGRES_HOST", "localhost"),
    "port":     int(os.getenv("POSTGRES_PORT", "5433")),
    "dbname":   os.getenv("POSTGRES_DB", "movie_recommender"),
    "user":     os.getenv("POSTGRES_USER", "postgres"),
    "password": os.getenv("POSTGRES_PASSWORD", ""),
}

CSV_DIR = Path("data/csv")

# Load order respects FK dependencies
# Format: (csv_filename_stem, postgres_table_name, [pk_columns_for_conflict])
LOAD_ORDER = [
    ("movies",          "movie",         ["movie_id"]),
    ("genres",          "genre",         ["genre_id"]),
    ("movie_genres",    "movie_genre",   ["movie_id", "genre_id"]),
    ("persons",         "person",        ["person_id"]),
    ("movie_cast",      "movie_cast",    ["movie_id", "person_id", "credit_id"]),
    ("movie_crew",      "movie_crew",    ["movie_id", "person_id", "credit_id"]),
    ("keywords",        "keyword",       ["keyword_id"]),
    ("movie_keywords",  "movie_keyword", ["movie_id", "keyword_id"]),
    ("companies",       "company",       ["company_id"]),
    ("movie_companies", "movie_company", ["movie_id", "company_id"]),
    ("countries",       "country",       ["country_code"]),
    ("movie_countries", "movie_country", ["movie_id", "country_code"]),
    ("reviews",         "review",        ["review_id"]),
    # derived / seeded tables — generated by fetch script from review authors
    ("tmdb_accounts",   "tmdb_account",  ["account_id"]),
    ("guest_sessions",  "guest_session", ["guest_session_id"]),
    ("user_ratings",    "user_rating",   ["account_id", "movie_id"]),
    ("guest_ratings",   "guest_rating",  ["guest_session_id", "movie_id"]),
]

# Columns that should become NULL when the CSV value is an empty string
NULLABLE_COLUMNS = {
    "movie":      {"release_date", "runtime", "popularity", "vote_average",
                   "vote_count", "budget", "revenue", "collection_id", "collection_name"},
    "person":     {"gender", "popularity"},
    "movie_cast":    {"cast_order", "cast_id"},   # credit_id is NOT NULL (part of PK)
    "review":        {"author_rating", "created_at", "updated_at"},
    "tmdb_account":  {"avatar_path"},
    "user_rating":   {"created_at"},
    "guest_rating":  {"created_at"},
    "guest_session": {"expires_at"},
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def clean_row(row: dict, table: str) -> dict:
    """Strip \\r from text fields and nullify designated empty columns."""
    nullable = NULLABLE_COLUMNS.get(table, set())
    cleaned = {}
    for k, v in row.items():
        if isinstance(v, str):
            v = v.replace("\r\n", "\n").replace("\r", " ").strip()
        if v == "" and k in nullable:
            v = None
        cleaned[k] = v
    return cleaned


def load_table_via_copy(cur, table: str, csv_path: Path) -> int:
    with open(csv_path, encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return 0
    columns = list(rows[0].keys())
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=columns, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow(clean_row(row, table))
    buf.seek(0)
    cur.copy_expert(
        f"COPY {table} ({', '.join(columns)}) FROM STDIN WITH (FORMAT csv, HEADER true, NULL '')",
        buf,
    )
    return len(rows)


def load_table_via_insert(cur, table: str, pk_cols: list, csv_path: Path) -> int:
    with open(csv_path, encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return 0
    columns = list(rows[0].keys())
    placeholders = ", ".join(f"%({c})s" for c in columns)
    conflict_target = ", ".join(pk_cols)
    sql = (
        f"INSERT INTO {table} ({', '.join(columns)}) "
        f"VALUES ({placeholders}) "
        f"ON CONFLICT ({conflict_target}) DO NOTHING"
    )
    for row in rows:
        cur.execute(sql, clean_row(row, table))
    return len(rows)


# ---------------------------------------------------------------------------
# Step 0 – Truncate all tables so re-runs start clean
# ---------------------------------------------------------------------------

# Root tables only; ON DELETE CASCADE in FK definitions wipes dependent tables.
_ROOT_TABLES = [
    "movie", "genre", "keyword", "company", "country",
    "person", "tmdb_account", "guest_session",
]

def truncate_all_tables(conn):
    print("\n[Step 0] Truncating all tables ...")
    tables = ", ".join(_ROOT_TABLES)
    with conn.cursor() as cur:
        cur.execute(f"TRUNCATE TABLE {tables} CASCADE;")
    conn.commit()
    print("  All tables cleared.")


# ---------------------------------------------------------------------------
# Step 1 – Load all CSV tables
# ---------------------------------------------------------------------------

def load_csv_tables(conn):
    print("\n[Step 1] Loading CSV tables ...")
    conn.autocommit = False

    with conn.cursor() as cur:
        for stem, table, pk_cols in LOAD_ORDER:
            csv_path = CSV_DIR / f"{stem}.csv"
            if not csv_path.exists():
                print(f"  [SKIP] {csv_path} not found")
                continue

            print(f"  {csv_path} -> {table} ...", end=" ", flush=True)
            try:
                count = load_table_via_copy(cur, table, csv_path)
                print(f"{count} rows (COPY)")
            except Exception as copy_err:
                conn.rollback()
                print(f"COPY failed ({copy_err}), retrying with INSERT ...", end=" ", flush=True)
                try:
                    with conn.cursor() as cur2:
                        count = load_table_via_insert(cur2, table, pk_cols, csv_path)
                        print(f"{count} rows (INSERT)")
                except Exception as insert_err:
                    conn.rollback()
                    print(f"\n[ERROR] {table}: {insert_err}")
                    continue

            conn.commit()

    print("  CSV tables loaded.")




# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    print("Connecting to PostgreSQL ...")
    print(f"  host={DB_CONFIG['host']}  port={DB_CONFIG['port']}  db={DB_CONFIG['dbname']}")

    try:
        conn = psycopg2.connect(**DB_CONFIG)
    except psycopg2.OperationalError as e:
        print(f"\n[ERROR] Cannot connect: {e}")
        print("Make sure the database is running and .env is correct.")
        sys.exit(1)

    try:
        truncate_all_tables(conn)
        load_csv_tables(conn)
    finally:
        conn.close()

    print("\nAll done.")


if __name__ == "__main__":
    main()
